/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class JFMusica extends javax.swing.JFrame {

    /**
     * Creates new form Musica
     */
    public JFMusica() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBExitMusica = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFTitulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFAlbum = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFDuracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jBAñadir = new javax.swing.JButton();
        jBVolverMusica = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jTFGrupo1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBExitMusica.setBackground(new java.awt.Color(102, 153, 255));
        jBExitMusica.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jBExitMusica.setForeground(new java.awt.Color(55, 55, 51));
        jBExitMusica.setText("Salir");
        jBExitMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(jBExitMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 60, 20));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 51));
        jLabel1.setText("Música");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 140, 40));

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Titulo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 50, -1));
        getContentPane().add(jTFTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText("Grupo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));
        getContentPane().add(jTFAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 110, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Duración");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 60, 20));

        jTFDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDuracionActionPerformed(evt);
            }
        });
        getContentPane().add(jTFDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 50, -1));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 55));
        jLabel6.setText("min");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        jBAñadir.setBackground(new java.awt.Color(255, 102, 51));
        jBAñadir.setForeground(new java.awt.Color(55, 55, 51));
        jBAñadir.setText("Añadir");
        getContentPane().add(jBAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jBVolverMusica.setBackground(new java.awt.Color(102, 204, 255));
        jBVolverMusica.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jBVolverMusica.setForeground(new java.awt.Color(55, 55, 51));
        jBVolverMusica.setText("Volver");
        jBVolverMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverMusicaActionPerformed(evt);
            }
        });
        getContentPane().add(jBVolverMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jButton2.setBackground(new java.awt.Color(255, 153, 51));
        jButton2.setForeground(new java.awt.Color(51, 51, 55));
        jButton2.setText("Favoritos");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 140, 120));

        jButton1.setBackground(new java.awt.Color(255, 102, 51));
        jButton1.setForeground(new java.awt.Color(51, 51, 55));
        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 80, -1));
        getContentPane().add(jTFGrupo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 110, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Album");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        Fondo.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/controles-musica.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 200, 590, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/imagenes/fondo_blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitMusicaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBExitMusicaActionPerformed

    private void jTFDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDuracionActionPerformed

    private void jBVolverMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBVolverMusicaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jBAñadir;
    private javax.swing.JButton jBExitMusica;
    private javax.swing.JButton jBVolverMusica;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFAlbum;
    private javax.swing.JTextField jTFDuracion;
    private javax.swing.JTextField jTFGrupo1;
    private javax.swing.JTextField jTFTitulo;
    // End of variables declaration//GEN-END:variables
}
