/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Usuario
 */
public class Alergenos extends javax.swing.JFrame {

    /**
     * Creates new form Alergenos
     */
    public Alergenos() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBVolverInvitados2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBAnadirAler = new javax.swing.JButton();
        jBExitAler = new javax.swing.JButton();
        jBVolverAler = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jBBorrarAler = new javax.swing.JButton();
        jTFNombreAler = new javax.swing.JTextField();
        jCBAler = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jBVolverInvitados2.setBackground(new java.awt.Color(102, 204, 255));
        jBVolverInvitados2.setForeground(new java.awt.Color(51, 51, 55));
        jBVolverInvitados2.setText("Borrar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(213, 44, 44));
        jLabel4.setText("Alérgenos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 160, 30));

        jBAnadirAler.setBackground(new java.awt.Color(213, 44, 44));
        jBAnadirAler.setForeground(new java.awt.Color(51, 51, 55));
        jBAnadirAler.setText("Añadir");
        getContentPane().add(jBAnadirAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 80, -1));

        jBExitAler.setBackground(new java.awt.Color(102, 153, 255));
        jBExitAler.setForeground(new java.awt.Color(51, 51, 55));
        jBExitAler.setText("Salir");
        jBExitAler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitAlerActionPerformed(evt);
            }
        });
        getContentPane().add(jBExitAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 70, -1));

        jBVolverAler.setBackground(new java.awt.Color(102, 204, 255));
        jBVolverAler.setForeground(new java.awt.Color(51, 51, 55));
        jBVolverAler.setText("Volver");
        getContentPane().add(jBVolverAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 80, -1));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 55));
        jLabel8.setText("Nombre :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 30));

        jBBorrarAler.setBackground(new java.awt.Color(213, 44, 44));
        jBBorrarAler.setForeground(new java.awt.Color(51, 51, 55));
        jBBorrarAler.setText("Borrar");
        getContentPane().add(jBBorrarAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, -1));
        getContentPane().add(jTFNombreAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 90, 20));

        jCBAler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jCBAler, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 150, -1));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/imagenes/Diferencia-entre-inflamacion-e-intolerancia-alimentaria.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 200));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/imagenes/fondo_blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 460, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitAlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitAlerActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBExitAlerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alergenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alergenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alergenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alergenos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alergenos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAnadirAler;
    private javax.swing.JButton jBBorrarAler;
    private javax.swing.JButton jBExitAler;
    private javax.swing.JButton jBVolverAler;
    private javax.swing.JButton jBVolverInvitados2;
    private javax.swing.JComboBox<String> jCBAler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFNombreAler;
    // End of variables declaration//GEN-END:variables
}
