/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Usuario
 */
public class Comida extends javax.swing.JFrame {

    /**
     * Creates new form Comida
     */
    public Comida() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ingrVisibles(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBVolverComida = new javax.swing.JButton();
        jBExitComida = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTFNombreComida = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFcantidadComida = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTFPrecioComida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jTFnombreIngr = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTFcantidadIngr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTFprecioIngr = new javax.swing.JTextField();
        jBFavComida = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jBanadirIngr = new javax.swing.JButton();
        jBIngr = new javax.swing.JButton();
        jBborrarIngr = new javax.swing.JButton();
        jBcalcularPrecio = new javax.swing.JButton();
        jBborrarComida = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jBanadirComida = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBVolverComida.setBackground(new java.awt.Color(102, 204, 255));
        jBVolverComida.setForeground(new java.awt.Color(55, 55, 51));
        jBVolverComida.setText("Volver");
        jBVolverComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverComidaActionPerformed(evt);
            }
        });
        getContentPane().add(jBVolverComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, -1));

        jBExitComida.setBackground(new java.awt.Color(102, 153, 255));
        jBExitComida.setForeground(new java.awt.Color(55, 55, 51));
        jBExitComida.setText("Salir");
        jBExitComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitComidaActionPerformed(evt);
            }
        });
        getContentPane().add(jBExitComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 80, -1));

        jLTitulo.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLTitulo.setForeground(new java.awt.Color(51, 51, 55));
        jLTitulo.setText("Comida");
        getContentPane().add(jLTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 150, 60));

        jLabel3.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 55));
        jLabel3.setText("Nombre :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 30));
        getContentPane().add(jTFNombreComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 140, 30));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 55));
        jLabel4.setText("Cantidad :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        jTFcantidadComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadComidaActionPerformed(evt);
            }
        });
        getContentPane().add(jTFcantidadComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 40, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 55));
        jLabel5.setText("Precio : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));
        getContentPane().add(jTFPrecioComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 40, -1));

        jLabel6.setForeground(new java.awt.Color(51, 51, 55));
        jLabel6.setText("€");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 10, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/imagenes/meal.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 240, 200));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 55));
        jLabel7.setText(" Ingredientes");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 110, 60));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 120, 90));

        jLabel8.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 55));
        jLabel8.setText("Nombre :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, 30));

        jTFnombreIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFnombreIngrActionPerformed(evt);
            }
        });
        getContentPane().add(jTFnombreIngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 140, 30));

        jLabel9.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 55));
        jLabel9.setText("Cantidad :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, -1, 20));

        jTFcantidadIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFcantidadIngrActionPerformed(evt);
            }
        });
        getContentPane().add(jTFcantidadIngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 40, -1));

        jLabel10.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 55));
        jLabel10.setText("Precio : ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jTFprecioIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFprecioIngrActionPerformed(evt);
            }
        });
        getContentPane().add(jTFprecioIngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 40, -1));

        jBFavComida.setBackground(new java.awt.Color(255, 153, 51));
        jBFavComida.setForeground(new java.awt.Color(51, 51, 55));
        jBFavComida.setText("Favoritos");
        getContentPane().add(jBFavComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel11.setForeground(new java.awt.Color(51, 51, 55));
        jLabel11.setText("€");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 10, 20));

        jBanadirIngr.setBackground(new java.awt.Color(255, 153, 153));
        jBanadirIngr.setForeground(new java.awt.Color(51, 51, 55));
        jBanadirIngr.setText("Añadir ");
        getContentPane().add(jBanadirIngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 80, 30));

        jBIngr.setBackground(new java.awt.Color(255, 102, 102));
        jBIngr.setForeground(new java.awt.Color(51, 51, 55));
        jBIngr.setText("Ingr");
        jBIngr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIngrActionPerformed(evt);
            }
        });
        getContentPane().add(jBIngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 80, -1));

        jBborrarIngr.setBackground(new java.awt.Color(255, 102, 102));
        jBborrarIngr.setForeground(new java.awt.Color(51, 51, 55));
        jBborrarIngr.setText("Borrar");
        getContentPane().add(jBborrarIngr, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 80, -1));

        jBcalcularPrecio.setBackground(new java.awt.Color(102, 204, 255));
        jBcalcularPrecio.setForeground(new java.awt.Color(51, 51, 55));
        jBcalcularPrecio.setText("Calcular Precio");
        getContentPane().add(jBcalcularPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 120, -1));

        jBborrarComida.setBackground(new java.awt.Color(255, 102, 102));
        jBborrarComida.setForeground(new java.awt.Color(51, 51, 55));
        jBborrarComida.setText("Borrar");
        getContentPane().add(jBborrarComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 80, -1));

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 180));

        jBanadirComida.setBackground(new java.awt.Color(255, 153, 153));
        jBanadirComida.setForeground(new java.awt.Color(51, 51, 55));
        jBanadirComida.setText("Añadir");
        jBanadirComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBanadirComidaActionPerformed(evt);
            }
        });
        getContentPane().add(jBanadirComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 80, -1));

        jLabel12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 55));
        jLabel12.setText("Añadir Ingrediente");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 40));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/imagenes/fondo_blanco.jpg"))); // NOI18N
        Fondo.setText("Precio");
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBVolverComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBVolverComidaActionPerformed

    private void jBExitComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitComidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBExitComidaActionPerformed

    private void jTFcantidadComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadComidaActionPerformed

    private void jTFcantidadIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFcantidadIngrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFcantidadIngrActionPerformed

    private void jTFprecioIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFprecioIngrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFprecioIngrActionPerformed

    private void jBIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIngrActionPerformed
        ingrVisibles(true);
    }//GEN-LAST:event_jBIngrActionPerformed

    public void ingrVisibles(boolean visible) {
        this.jBanadirIngr.setVisible(visible);
        this.jBborrarIngr.setVisible(visible);
        this.jTFcantidadIngr.setVisible(visible);
        this.jTFnombreIngr.setVisible(visible);
        this.jTFprecioIngr.setVisible(visible);
        this.jLabel6.setVisible(visible);
        this.jLabel7.setVisible(visible);
        this.jLabel8.setVisible(visible);
        this.jLabel9.setVisible(visible);
        this.jLabel10.setVisible(visible);
        this.jLabel12.setVisible(visible);
        this.jBcalcularPrecio.setVisible(visible);
        this.jScrollPane2.setVisible(visible);
    }

    private void jTFnombreIngrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFnombreIngrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFnombreIngrActionPerformed

    private void jBanadirComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBanadirComidaActionPerformed
        this.ingrVisibles(false);
    }//GEN-LAST:event_jBanadirComidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Comida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Comida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton jBExitComida;
    private javax.swing.JButton jBFavComida;
    private javax.swing.JButton jBIngr;
    private javax.swing.JButton jBVolverComida;
    private javax.swing.JButton jBanadirComida;
    private javax.swing.JButton jBanadirIngr;
    private javax.swing.JButton jBborrarComida;
    private javax.swing.JButton jBborrarIngr;
    private javax.swing.JButton jBcalcularPrecio;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTFNombreComida;
    private javax.swing.JTextField jTFPrecioComida;
    private javax.swing.JTextField jTFcantidadComida;
    private javax.swing.JTextField jTFcantidadIngr;
    private javax.swing.JTextField jTFnombreIngr;
    private javax.swing.JTextField jTFprecioIngr;
    // End of variables declaration//GEN-END:variables
}
