/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Usuario
 */
public class Fechas extends javax.swing.JFrame {

    /**
     * Creates new form Fechas
     */
    public Fechas() {
      this.setLocation(WIDTH+350, WIDTH+200);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDCFchIni = new com.toedter.calendar.JDateChooser();
        jDCFchSalida = new com.toedter.calendar.JDateChooser();
        jBExitFiesta = new javax.swing.JButton();
        jBVolverFiesta = new javax.swing.JButton();
        jCBmismoDia = new javax.swing.JCheckBox();
        jFFHoraSalida = new javax.swing.JFormattedTextField();
        jFFHoraIni = new javax.swing.JFormattedTextField();
        jBVolverFiesta1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDCFchIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 120, -1));
        getContentPane().add(jDCFchSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 120, -1));

        jBExitFiesta.setBackground(new java.awt.Color(102, 153, 255));
        jBExitFiesta.setForeground(new java.awt.Color(55, 55, 51));
        jBExitFiesta.setText("Salir");
        jBExitFiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExitFiestaActionPerformed(evt);
            }
        });
        getContentPane().add(jBExitFiesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 70, -1));

        jBVolverFiesta.setBackground(new java.awt.Color(102, 204, 255));
        jBVolverFiesta.setForeground(new java.awt.Color(55, 55, 51));
        jBVolverFiesta.setText("Enviar");
        jBVolverFiesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverFiestaActionPerformed(evt);
            }
        });
        getContentPane().add(jBVolverFiesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        jCBmismoDia.setBackground(new java.awt.Color(222, 222, 222));
        jCBmismoDia.setForeground(new java.awt.Color(51, 51, 55));
        jCBmismoDia.setText("Entrada y salida en el mismo dia");
        jCBmismoDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBmismoDiaActionPerformed(evt);
            }
        });
        getContentPane().add(jCBmismoDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 250, -1));

        jFFHoraSalida.setText("00:00");
        getContentPane().add(jFFHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 70, -1));

        jFFHoraIni.setText("00:00");
        getContentPane().add(jFFHoraIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 70, -1));

        jBVolverFiesta1.setBackground(new java.awt.Color(102, 204, 255));
        jBVolverFiesta1.setForeground(new java.awt.Color(55, 55, 51));
        jBVolverFiesta1.setText("Volver");
        jBVolverFiesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVolverFiesta1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBVolverFiesta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 55));
        jLabel7.setText("Hora Final");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 55));
        jLabel4.setText("Hora Inicial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 55));
        jLabel5.setText("Fecha de salida");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 55));
        jLabel3.setText("Fecha y hora");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 170, 60));

        jLabel6.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 55));
        jLabel6.setText("Fecha Inicial");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/imagenes/Sin título.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 30, -1, 420));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ventanas/imagenes/fondo_blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBExitFiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExitFiestaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBExitFiestaActionPerformed

    private void jBVolverFiestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverFiestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBVolverFiestaActionPerformed

    private void jBVolverFiesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVolverFiesta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBVolverFiesta1ActionPerformed

    private void jCBmismoDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBmismoDiaActionPerformed
        if(this.jCBmismoDia.isSelected()){
            this.jDCFchSalida.setDate(this.jDCFchIni.getDate());
            
        }else{
           this.jDCFchSalida.setDate(null);
            
        }
    }//GEN-LAST:event_jCBmismoDiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fechas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBExitFiesta;
    private javax.swing.JButton jBVolverFiesta;
    private javax.swing.JButton jBVolverFiesta1;
    private javax.swing.JCheckBox jCBmismoDia;
    private com.toedter.calendar.JDateChooser jDCFchIni;
    private com.toedter.calendar.JDateChooser jDCFchSalida;
    private javax.swing.JFormattedTextField jFFHoraIni;
    private javax.swing.JFormattedTextField jFFHoraSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
